import {IColors} from "@/types";

export const colorList: IColors[] = [
{ hex: "#000000",	name: "Black (W3C)"},
{ hex: "#0C090A",	name: "Night"},
{ hex: "#34282C",	name: "Charcoal"},
{ hex: "#3B3131",	name: "Oil"},
{ hex: "#3A3B3C",	name: "Dark Gray"},
{ hex: "#454545",	name: "Light Black"},
{ hex: "#413839",	name: "Black Cat"},
{ hex: "#3D3C3A",	name: "Iridium"},
{ hex: "#463E3F",	name: "Black Eel"},
{ hex: "#4C4646",	name: "Black Cow"},
{ hex: "#504A4B",	name: "Gray Wolf"},
{ hex: "#565051",	name: "Vampire Gray"},
{ hex: "#52595D",	name: "Iron Gray"},
{ hex: "#5C5858",	name: "Gray Dolphin"},
{ hex: "#625D5D",	name: "Carbon Gray"},
{ hex: "#666362",	name: "Ash Gray"},
{ hex: "#696969",	name: "DimGray or DimGrey (W3C)"},
{ hex: "#686A6C",	name: "Nardo Gray"},
{ hex: "#6D6968",	name: "Cloudy Gray"},
{ hex: "#726E6D",	name: "Smokey Gray"},
{ hex: "#736F6E",	name: "Alien Gray"},
{ hex: "#757575",	name: "Sonic Silver"},
{ hex: "#797979",	name: "Platinum Gray"},
{ hex: "#837E7C",	name: "Granite"},
{ hex: "#808080",	name: "Gray or Grey (W3C)"},
{ hex: "#848482",	name: "Battleship Gray"},
{ hex: "#8D918D",	name: "Gunmetal Gray"},
{ hex: "#A9A9A9",	name: "DarkGray or DarkGrey (W3C)"},
{ hex: "#B6B6B4",	name: "Gray Cloud"},
{ hex: "#C0C0C0",	name: "Silver (W3C)"},
{ hex: "#C9C0BB",	name: "Pale Silver"},
{ hex: "#D1D0CE",	name: "Gray Goose"},
{ hex: "#CECECE",	name: "Platinum Silver"},
{ hex: "#D3D3D3",	name: "LightGray or LightGrey (W3C)"},
{ hex: "#DADBDD",	name: "Silver White"},
{ hex: "#DCDCDC",	name: "Gainsboro (W3C)"},
{ hex: "#E5E4E2",	name: "Platinum"},
{ hex: "#BCC6CC",	name: "Metallic Silver"},
{ hex: "#98AFC7",	name: "Blue Gray"},
{ hex: "#838996",	name: "Roman Silver"},
{ hex: "#778899",	name: "LightSlateGray or LightSlateGrey (W3C)"},
{ hex: "#708090",	name: "SlateGray or SlateGrey (W3C)"},
{ hex: "#6D7B8D",	name: "Rat Gray"},
{ hex: "#657383",	name: "Slate Granite Gray"},
{ hex: "#616D7E",	name: "Jet Gray"},
{ hex: "#646D7E",	name: "Mist Blue"},
{ hex: "#566D7E",	name: "Marble Blue"},
{ hex: "#737CA1",	name: "Slate Blue Grey"},
{ hex: "#728FCE",	name: "Light Purple Blue"},
{ hex: "#4863A0",	name: "Azure Blue"},
{ hex: "#2B547E",	name: "Blue Jay"},
{ hex: "#36454F",	name: "Charcoal Blue"},
{ hex: "#29465B",	name: "Dark Blue Grey"},
{ hex: "#2B3856",	name: "Dark Slate"},
{ hex: "#123456",	name: "Deep-Sea Blue"},
{ hex: "#151B54",	name: "Night Blue"},
{ hex: "#191970",	name: "MidnightBlue (W3C)"},
{ hex: "#000080",	name: "Navy (W3C)"},
{ hex: "#151B8D",	name: "Denim Dark Blue"},
{ hex: "#00008B",	name: "DarkBlue (W3C)"},
{ hex: "#15317E",	name: "Lapis Blue"},
{ hex: "#0000A0",	name: "New Midnight Blue"},
{ hex: "#0000A5",	name: "Earth Blue"},
{ hex: "#0020C2",	name: "Cobalt Blue"},
{ hex: "#0000CD",	name: "MediumBlue (W3C)"},
{ hex: "#0041C2",	name: "Blueberry Blue"},
{ hex: "#2916F5",	name: "Canary Blue"},
{ hex: "#0000FF",	name: "Blue (W3C)"},
{ hex: "#0002FF",	name: "Samco Blue"},
{ hex: "#0909FF",	name: "Bright Blue"},
{ hex: "#1F45FC",	name: "Blue Orchid"},
{ hex: "#2554C7",	name: "Sapphire Blue"},
{ hex: "#1569C7",	name: "Blue Eyes"},
{ hex: "#1974D2",	name: "Bright Navy Blue"},
{ hex: "#2B60DE",	name: "Balloon Blue"},
{ hex: "#4169E1",	name: "RoyalBlue (W3C)"},
{ hex: "#2B65EC",	name: "Ocean Blue"},
{ hex: "#306EFF",	name: "Blue Ribbon"},
{ hex: "#157DEC",	name: "Blue Dress"},
{ hex: "#1589FF",	name: "Neon Blue"},
{ hex: "#1E90FF",	name: "DodgerBlue (W3C)"},
{ hex: "#368BC1",	name: "Glacial Blue Ice"},
{ hex: "#4682B4",	name: "SteelBlue (W3C)"},
{ hex: "#488AC7",	name: "Silk Blue"},
{ hex: "#357EC7",	name: "Windows Blue"},
{ hex: "#3090C7",	name: "Blue Ivy"},
{ hex: "#659EC7",	name: "Blue Koi"},
{ hex: "#87AFC7",	name: "Columbia Blue"},
{ hex: "#95B9C7",	name: "Baby Blue"},
{ hex: "#6495ED",	name: "CornflowerBlue (W3C)"},
{ hex: "#6698FF",	name: "Sky Blue Dress"},
{ hex: "#56A5EC",	name: "Iceberg"},
{ hex: "#38ACEC",	name: "Butterfly Blue"},
{ hex: "#00BFFF",	name: "DeepSkyBlue (W3C)"},
{ hex: "#3BB9FF",	name: "Midday Blue"},
{ hex: "#5CB3FF",	name: "Crystal Blue"},
{ hex: "#79BAEC",	name: "Denim Blue"},
{ hex: "#82CAFF",	name: "Day Sky Blue"},
{ hex: "#87CEFA",	name: "LightSkyBlue (W3C)"},
{ hex: "#87CEEB",	name: "SkyBlue (W3C)"},
{ hex: "#A0CFEC",	name: "Jeans Blue"},
{ hex: "#B7CEEC",	name: "Blue Angel"},
{ hex: "#B4CFEC",	name: "Pastel Blue"},
{ hex: "#ADDFFF",	name: "Light Day Blue"},
{ hex: "#C2DFFF",	name: "Sea Blue"},
{ hex: "#C6DEFF",	name: "Heavenly Blue"},
{ hex: "#BDEDFF",	name: "Robin Egg Blue"},
{ hex: "#B0E0E6",	name: "PowderBlue (W3C)"},
{ hex: "#AFDCEC",	name: "Coral Blue"},
{ hex: "#ADD8E6",	name: "LightBlue (W3C)"},
{ hex: "#B0CFDE",	name: "LightSteelBlue (W3C)"},
{ hex: "#C9DFEC",	name: "Gulf Blue"},
{ hex: "#D5D6EA",	name: "Pastel Light Blue"},
{ hex: "#E3E4FA",	name: "Lavender Blue"},
{ hex: "#DBE9FA",	name: "White Blue"},
{ hex: "#E6E6FA",	name: "Lavender (W3C)"},
{ hex: "#EBF4FA",	name: "Water"},
{ hex: "#F0F8FF",	name: "AliceBlue (W3C)"},
{ hex: "#F8F8FF",	name: "GhostWhite (W3C)"},
{ hex: "#F0FFFF",	name: "Azure (W3C)"},
{ hex: "#E0FFFF",	name: "LightCyan (W3C)"},
{ hex: "#CCFFFF",	name: "Light Slate"},
{ hex: "#9AFEFF",	name: "Electric Blue"},
{ hex: "#7DFDFE",	name: "Tron Blue"},
{ hex: "#57FEFF",	name: "Blue Zircon"},
{ hex: "#00FFFF",	name: "Aqua or Cyan (W3C)"},
{ hex: "#0AFFFF",	name: "Bright Cyan"},
{ hex: "#50EBEC",	name: "Celeste"},
{ hex: "#4EE2EC",	name: "Blue Diamond"},
{ hex: "#16E2F5",	name: "Bright Turquoise"},
{ hex: "#8EEBEC",	name: "Blue Lagoon"},
{ hex: "#AFEEEE",	name: "PaleTurquoise (W3C)"},
{ hex: "#CFECEC",	name: "Pale Blue Lily"},
{ hex: "#B3D9D9",	name: "Light Teal"},
{ hex: "#81D8D0",	name: "Tiffany Blue"},
{ hex: "#77BFC7",	name: "Blue Hosta"},
{ hex: "#92C7C7",	name: "Cyan Opaque"},
{ hex: "#78C7C7",	name: "Northern Lights Blue"},
{ hex: "#7BCCB5",	name: "Blue Green"},
{ hex: "#66CDAA",	name: "MediumAquaMarine (W3C)"},
{ hex: "#AAF0D1",	name: "Magic Mint"},
{ hex: "#93FFE8",	name: "Light Aquamarine"},
{ hex: "#7FFFD4",	name: "Aquamarine (W3C)"},
{ hex: "#01F9C6",	name: "Bright Teal"},
{ hex: "#40E0D0",	name: "Turquoise (W3C)"},
{ hex: "#48D1CC",	name: "MediumTurquoise (W3C)"},
{ hex: "#48CCCD",	name: "Deep Turquoise"},
{ hex: "#46C7C7",	name: "Jellyfish"},
{ hex: "#43C6DB",	name: "Blue Turquoise"},
{ hex: "#00CED1",	name: "DarkTurquoise (W3C)"},
{ hex: "#43BFC7",	name: "Macaw Blue Green"},
{ hex: "#20B2AA",	name: "LightSeaGreen (W3C)"},
{ hex: "#3EA99F",	name: "Seafoam Green"},
{ hex: "#5F9EA0",	name: "CadetBlue (W3C)"},
{ hex: "#3B9C9C",	name: "Deep-Sea"},
{ hex: "#008B8B",	name: "DarkCyan (W3C)"},
{ hex: "#00827F",	name: "Teal Green"},
{ hex: "#008080",	name: "Teal (W3C)"},
{ hex: "#007C80",	name: "Teal Blue"},
{ hex: "#045F5F",	name: "Medium Teal"},
{ hex: "#045D5D",	name: "Dark Teal"},
{ hex: "#033E3E",	name: "Deep Teal"},
{ hex: "#25383C",	name: "DarkSlateGray or DarkSlateGrey (W3C)"},
{ hex: "#2C3539",	name: "Gunmetal"},
{ hex: "#3C565B",	name: "Blue Moss Green"},
{ hex: "#4C787E",	name: "Beetle Green"},
{ hex: "#5E7D7E",	name: "Grayish Turquoise"},
{ hex: "#307D7E",	name: "Greenish Blue"},
{ hex: "#348781",	name: "Aquamarine Stone"},
{ hex: "#438D80",	name: "Sea Turtle Green"},
{ hex: "#4E8975",	name: "Dull-Sea Green"},
{ hex: "#1F6357",	name: "Dark Green Blue"},
{ hex: "#306754",	name: "Deep-Sea Green"},
{ hex: "#006A4E",	name: "Bottle Green"},
{ hex: "#2E8B57",	name: "SeaGreen (W3C)"},
{ hex: "#1B8A6B",	name: "Elf Green"},
{ hex: "#31906E",	name: "Dark Mint"},
{ hex: "#00A36C",	name: "Jade"},
{ hex: "#34A56F",	name: "Earth Green"},
{ hex: "#1AA260",	name: "Chrome Green"},
{ hex: "#50C878",	name: "Emerald"},
{ hex: "#3EB489",	name: "Mint"},
{ hex: "#3CB371",	name: "MediumSeaGreen (W3C)"},
{ hex: "#7C9D8E",	name: "Metallic Green"},
{ hex: "#78866B",	name: "Camouflage Green"},
{ hex: "#848B79",	name: "Sage Green"},
{ hex: "#617C58",	name: "Hazel Green"},
{ hex: "#728C00",	name: "Venom Green"},
{ hex: "#6B8E23",	name: "OliveDrab (W3C)"},
{ hex: "#808000",	name: "Olive (W3C)"},
{ hex: "#556B2F",	name: "DarkOliveGreen (W3C)"},
{ hex: "#4E5B31",	name: "Military Green"},
{ hex: "#3A5F0B",	name: "Green Leaves"},
{ hex: "#4B5320",	name: "Army Green"},
{ hex: "#667C26",	name: "Fern Green"},
{ hex: "#4E9258",	name: "Fall Forest Green"},
{ hex: "#08A04B",	name: "Irish Green"},
{ hex: "#387C44",	name: "Pine Green"},
{ hex: "#347235",	name: "Medium Forest Green"},
{ hex: "#347C2C",	name: "Jungle Green"},
{ hex: "#227442",	name: "Cactus Green"},
{ hex: "#228B22",	name: "ForestGreen (W3C)"},
{ hex: "#008000",	name: "Green (W3C)"},
{ hex: "#006400",	name: "DarkGreen (W3C)"},
{ hex: "#056608",	name: "Deep Green"},
{ hex: "#046307",	name: "Deep Emerald Green"},
{ hex: "#355E3B",	name: "Hunter Green"},
{ hex: "#254117",	name: "Dark Forest Green"},
{ hex: "#004225",	name: "Lotus Green"},
{ hex: "#437C17",	name: "Seaweed Green"},
{ hex: "#347C17",	name: "Shamrock Green"},
{ hex: "#6AA121",	name: "Green Onion"},
{ hex: "#8A9A5B",	name: "Moss Green"},
{ hex: "#3F9B0B",	name: "Grass Green"},
{ hex: "#4AA02C",	name: "Green Pepper"},
{ hex: "#41A317",	name: "Dark Lime Green"},
{ hex: "#12AD2B",	name: "Parrot Green"},
{ hex: "#3EA055",	name: "Clover Green"},
{ hex: "#73A16C",	name: "Dinosaur Green"},
{ hex: "#6CBB3C",	name: "Green Snake"},
{ hex: "#6CC417",	name: "Alien Green"},
{ hex: "#4CC417",	name: "Green Apple"},
{ hex: "#32CD32",	name: "LimeGreen (W3C)"},
{ hex: "#52D017",	name: "Pea Green"},
{ hex: "#4CC552",	name: "Kelly Green"},
{ hex: "#54C571",	name: "Zombie Green"},
{ hex: "#89C35C",	name: "Green Peas"},
{ hex: "#85BB65",	name: "Dollar Bill Green"},
{ hex: "#99C68E",	name: "Frog Green"},
{ hex: "#A0D6B4",	name: "Turquoise Green"},
{ hex: "#8FBC8F",	name: "DarkSeaGreen (W3C)"},
{ hex: "#829F82",	name: "Basil Green"},
{ hex: "#A2AD9C",	name: "Gray Green"},
{ hex: "#9CB071",	name: "Iguana Green"},
{ hex: "#8FB31D",	name: "Citron Green"},
{ hex: "#B0BF1A",	name: "Acid Green"},
{ hex: "#B2C248",	name: "Avocado Green"},
{ hex: "#9DC209",	name: "Pistachio Green"},
{ hex: "#A1C935",	name: "Salad Green"},
{ hex: "#9ACD32",	name: "YellowGreen (W3C)"},
{ hex: "#77DD77",	name: "Pastel Green"},
{ hex: "#7FE817",	name: "Hummingbird Green"},
{ hex: "#59E817",	name: "Nebula Green"},
{ hex: "#57E964",	name: "Stoplight Go Green"},
{ hex: "#16F529",	name: "Neon Green"},
{ hex: "#5EFB6E",	name: "Jade Green"},
{ hex: "#36F57F",	name: "Lime Mint Green"},
{ hex: "#00FF7F",	name: "SpringGreen (W3C)"},
{ hex: "#00FA9A",	name: "MediumSpringGreen (W3C)"},
{ hex: "#5FFB17",	name: "Emerald Green"},
{ hex: "#00FF00",	name: "Lime (W3C)"},
{ hex: "#7CFC00",	name: "LawnGreen (W3C)"},
{ hex: "#66FF00",	name: "Bright Green"},
{ hex: "#7FFF00",	name: "Chartreuse (W3C)"},
{ hex: "#87F717",	name: "Yellow Lawn Green"},
{ hex: "#98F516",	name: "Aloe Vera Green"},
{ hex: "#B1FB17",	name: "Dull Green Yellow"},
{ hex: "#ADF802",	name: "Lemon Green"},
{ hex: "#ADFF2F",	name: "GreenYellow (W3C)"},
{ hex: "#BDF516",	name: "Chameleon Green"},
{ hex: "#DAEE01",	name: "Neon Yellow Green"},
{ hex: "#E2F516",	name: "Yellow Green Grosbeak"},
{ hex: "#CCFB5D",	name: "Tea Green"},
{ hex: "#BCE954",	name: "Slime Green"},
{ hex: "#64E986",	name: "Algae Green"},
{ hex: "#90EE90",	name: "LightGreen (W3C)"},
{ hex: "#6AFB92",	name: "Dragon Green"},
{ hex: "#98FB98",	name: "PaleGreen (W3C)"},
{ hex: "#98FF98",	name: "Mint Green"},
{ hex: "#B5EAAA",	name: "Green Thumb"},
{ hex: "#E3F9A6",	name: "Organic Brown"},
{ hex: "#C3FDB8",	name: "Light Jade"},
{ hex: "#C2E5D3",	name: "Light Mint Green"},
{ hex: "#DBF9DB",	name: "Light Rose Green"},
{ hex: "#E8F1D4",	name: "Chrome White"},
{ hex: "#F0FFF0",	name: "HoneyDew (W3C)"},
{ hex: "#F5FFFA",	name: "MintCream (W3C)"},
{ hex: "#FFFACD",	name: "LemonChiffon (W3C)"},
{ hex: "#FFFFC2",	name: "Parchment"},
{ hex: "#FFFFCC",	name: "Cream"},
{ hex: "#FFFDD0",	name: "Cream White"},
{ hex: "#FAFAD2",	name: "LightGoldenRodYellow (W3C)"},
{ hex: "#FFFFE0",	name: "LightYellow (W3C)"},
{ hex: "#F5F5DC",	name: "Beige (W3C)"},
{ hex: "#FFF8DC",	name: "Cornsilk (W3C)"},
{ hex: "#FBF6D9",	name: "Blonde"},
{ hex: "#F7E7CE",	name: "Champagne"},
{ hex: "#FAEBD7",	name: "AntiqueWhite (W3C)"},
{ hex: "#FFEFD5",	name: "PapayaWhip (W3C)"},
{ hex: "#FFEBCD",	name: "BlanchedAlmond (W3C)"},
{ hex: "#FFE4C4",	name: "Bisque (W3C)"},
{ hex: "#F5DEB3",	name: "Wheat (W3C)"},
{ hex: "#FFE4B5",	name: "Moccasin (W3C)"},
{ hex: "#FFE5B4",	name: "Peach"},
{ hex: "#FED8B1",	name: "Light Orange"},
{ hex: "#FFDAB9",	name: "PeachPuff (W3C)"},
{ hex: "#FBD5AB",	name: "Coral Peach"},
{ hex: "#FFDEAD",	name: "NavajoWhite (W3C)"},
{ hex: "#FBE7A1",	name: "Golden Blonde"},
{ hex: "#F3E3C3",	name: "Golden Silk"},
{ hex: "#F0E2B6",	name: "Dark Blonde"},
{ hex: "#F1E5AC",	name: "Light Gold"},
{ hex: "#F3E5AB",	name: "Vanilla"},
{ hex: "#ECE5B6",	name: "Tan Brown"},
{ hex: "#E8E4C9",	name: "Dirty White"},
{ hex: "#EEE8AA",	name: "PaleGoldenRod (W3C)"},
{ hex: "#F0E68C",	name: "Khaki (W3C)"},
{ hex: "#EDDA74",	name: "Cardboard Brown"},
{ hex: "#EDE275",	name: "Harvest Gold"},
{ hex: "#FFE87C",	name: "Sun Yellow"},
{ hex: "#FFF380",	name: "Corn Yellow"},
{ hex: "#FAF884",	name: "Pastel Yellow"},
{ hex: "#FFFF33",	name: "Neon Yellow"},
{ hex: "#FFFF00",	name: "Yellow (W3C)"},
{ hex: "#FFEF00",	name: "Canary Yellow"},
{ hex: "#F5E216",	name: "Banana Yellow"},
{ hex: "#FFDB58",	name: "Mustard Yellow"},
{ hex: "#FFDF00",	name: "Golden Yellow"},
{ hex: "#F9DB24",	name: "Bold Yellow"},
{ hex: "#FFD801",	name: "Rubber Ducky Yellow"},
{ hex: "#FFD700",	name: "Gold (W3C)"},
{ hex: "#FDD017",	name: "Bright Gold"},
{ hex: "#FFCE44",	name: "Chrome Gold"},
{ hex: "#EAC117",	name: "Golden Brown"},
{ hex: "#F6BE00",	name: "Deep Yellow"},
{ hex: "#F2BB66",	name: "Macaroni and Cheese"},
{ hex: "#FBB917",	name: "Saffron"},
{ hex: "#FDBD01",	name: "Neon Gold"},
{ hex: "#FBB117",	name: "Beer"},
{ hex: "#FFAE42",	name: "Yellow Orange or Orange Yellow"},
{ hex: "#FFA62F",	name: "Cantaloupe"},
{ hex: "#FFA600",	name: "Cheese Orange"},
{ hex: "#FFA500",	name: "Orange (W3C)"},
{ hex: "#EE9A4D",	name: "Brown Sand"},
{ hex: "#F4A460",	name: "SandyBrown (W3C)"},
{ hex: "#E2A76F",	name: "Brown Sugar"},
{ hex: "#C19A6B",	name: "Camel Brown"},
{ hex: "#E6BF83",	name: "Deer Brown"},
{ hex: "#DEB887",	name: "BurlyWood (W3C)"},
{ hex: "#D2B48C",	name: "Tan (W3C)"},
{ hex: "#C8AD7F",	name: "Light French Beige"},
{ hex: "#C2B280",	name: "Sand"},
{ hex: "#BCB88A",	name: "Sage"},
{ hex: "#C8B560",	name: "Fall Leaf Brown"},
{ hex: "#C9BE62",	name: "Ginger Brown"},
{ hex: "#C9AE5D",	name: "Bronze Gold"},
{ hex: "#BDB76B",	name: "DarkKhaki (W3C)"},
{ hex: "#BAB86C",	name: "Olive Green"},
{ hex: "#B5A642",	name: "Brass"},
{ hex: "#C7A317",	name: "Cookie Brown"},
{ hex: "#D4AF37",	name: "Metallic Gold"},
{ hex: "#E9AB17",	name: "Bee Yellow"},
{ hex: "#E8A317",	name: "School Bus Yellow"},
{ hex: "#DAA520",	name: "GoldenRod (W3C)"},
{ hex: "#D4A017",	name: "Orange Gold"},
{ hex: "#C68E17",	name: "Caramel"},
{ hex: "#B8860B",	name: "DarkGoldenRod (W3C)"},
{ hex: "#C58917",	name: "Cinnamon"},
{ hex: "#CD853F",	name: "Peru (W3C)"},
{ hex: "#CD7F32",	name: "Bronze"},
{ hex: "#C88141",	name: "Tiger Orange"},
{ hex: "#B87333",	name: "Copper"},
{ hex: "#AA6C39",	name: "Dark Gold"},
{ hex: "#A97142",	name: "Metallic Bronze"},
{ hex: "#AB784E",	name: "Dark Almond"},
{ hex: "#966F33",	name: "Wood"},
{ hex: "#806517",	name: "Oak Brown"},
{ hex: "#665D1E",	name: "Antique Bronze"},
{ hex: "#8E7618",	name: "Hazel"},
{ hex: "#8B8000",	name: "Dark Yellow"},
{ hex: "#827839",	name: "Dark Moccasin"},
{ hex: "#8A865D",	name: "Khaki Green"},
{ hex: "#93917C",	name: "Millennium Jade"},
{ hex: "#9F8C76",	name: "Dark Beige"},
{ hex: "#AF9B60",	name: "Bullet Shell"},
{ hex: "#827B60",	name: "Army Brown"},
{ hex: "#786D5F",	name: "Sandstone"},
{ hex: "#483C32",	name: "Taupe"},
{ hex: "#493D26",	name: "Mocha"},
{ hex: "#513B1C",	name: "Milk Chocolate"},
{ hex: "#3D3635",	name: "Gray Brown"},
{ hex: "#3B2F2F",	name: "Dark Coffee"},
{ hex: "#43302E",	name: "Old Burgundy"},
{ hex: "#49413F",	name: "Western Charcoal"},
{ hex: "#5C3317",	name: "Bakers Brown"},
{ hex: "#654321",	name: "Dark Brown"},
{ hex: "#704214",	name: "Sepia Brown"},
{ hex: "#804A00",	name: "Dark Bronze"},
{ hex: "#6F4E37",	name: "Coffee"},
{ hex: "#835C3B",	name: "Brown Bear"},
{ hex: "#7F5217",	name: "Red Dirt"},
{ hex: "#7F462C",	name: "Sepia"},
{ hex: "#A0522D",	name: "Sienna (W3C)"},
{ hex: "#8B4513",	name: "SaddleBrown (W3C)"},
{ hex: "#8A4117",	name: "Dark Sienna"},
{ hex: "#7E3817",	name: "Sangria"},
{ hex: "#7E3517",	name: "Blood Red"},
{ hex: "#954535",	name: "Chestnut"},
{ hex: "#9E4638",	name: "Coral Brown"},
{ hex: "#C34A2C",	name: "Chestnut Red"},
{ hex: "#C04000",	name: "Mahogany"},
{ hex: "#EB5406",	name: "Red Gold"},
{ hex: "#C35817",	name: "Red Fox"},
{ hex: "#B86500",	name: "Dark Bisque"},
{ hex: "#B5651D",	name: "Light Brown"},
{ hex: "#B76734",	name: "Petra Gold"},
{ hex: "#C36241",	name: "Rust"},
{ hex: "#CB6D51",	name: "Copper Red"},
{ hex: "#C47451",	name: "Orange Salmon"},
{ hex: "#D2691E",	name: "Chocolate (W3C)"},
{ hex: "#CC6600",	name: "Sedona"},
{ hex: "#E56717",	name: "Papaya Orange"},
{ hex: "#E66C2C",	name: "Halloween Orange"},
{ hex: "#FF6700",	name: "Neon Orange"},
{ hex: "#FF5F1F",	name: "Bright Orange"},
{ hex: "#F87217",	name: "Pumpkin Orange"},
{ hex: "#F88017",	name: "Carrot Orange"},
{ hex: "#FF8C00",	name: "DarkOrange (W3C)"},
{ hex: "#F87431",	name: "Construction Cone Orange"},
{ hex: "#FF7722",	name: "Indian Saffron"},
{ hex: "#E67451",	name: "Sunrise Orange"},
{ hex: "#FF8040",	name: "Mango Orange"},
{ hex: "#FF7F50",	name: "Coral (W3C)"},
{ hex: "#F88158",	name: "Basket Ball Orange"},
{ hex: "#F9966B",	name: "Light Salmon Rose"},
{ hex: "#FFA07A",	name: "LightSalmon (W3C)"},
{ hex: "#E9967A",	name: "DarkSalmon (W3C)"},
{ hex: "#E78A61",	name: "Tangerine"},
{ hex: "#DA8A67",	name: "Light Copper"},
{ hex: "#FF8674",	name: "Salmon Pink"},
{ hex: "#FA8072",	name: "Salmon (W3C)"},
{ hex: "#F98B88",	name: "Peach Pink"},
{ hex: "#F08080",	name: "LightCoral (W3C)"},
{ hex: "#F67280",	name: "Pastel Red"},
{ hex: "#E77471",	name: "Pink Coral"},
{ hex: "#F75D59",	name: "Bean Red"},
{ hex: "#E55451",	name: "Valentine Red"},
{ hex: "#CD5C5C",	name: "IndianRed (W3C)"},
{ hex: "#FF6347",	name: "Tomato (W3C)"},
{ hex: "#E55B3C",	name: "Shocking Orange"},
{ hex: "#FF4500",	name: "OrangeRed (W3C)"},
{ hex: "#FF0000",	name: "Red (W3C)"},
{ hex: "#FD1C03",	name: "Neon Red"},
{ hex: "#FF2400",	name: "Scarlet Red"},
{ hex: "#F62217",	name: "Ruby Red"},
{ hex: "#F70D1A",	name: "Ferrari Red"},
{ hex: "#F62817",	name: "Fire Engine Red"},
{ hex: "#E42217",	name: "Lava Red"},
{ hex: "#E41B17",	name: "Love Red"},
{ hex: "#DC381F",	name: "Grapefruit"},
{ hex: "#C24641",	name: "Cherry Red"},
{ hex: "#C11B17",	name: "Chilli Pepper"},
{ hex: "#B22222",	name: "FireBrick (W3C)"},
{ hex: "#B21807",	name: "Tomato Sauce Red"},
{ hex: "#A52A2A",	name: "Brown (W3C)"},
{ hex: "#A70D2A",	name: "Carbon Red"},
{ hex: "#9F000F",	name: "Cranberry"},
{ hex: "#931314",	name: "Saffron Red"},
{ hex: "#990000",	name: "Crimson Red"},
{ hex: "#990012",	name: "Red Wine or Wine Red"},
{ hex: "#8B0000",	name: "DarkRed (W3C)"},
{ hex: "#800000",	name: "Maroon (W3C)"},
{ hex: "#8C001A",	name: "Burgundy"},
{ hex: "#7E191B",	name: "Vermilion"},
{ hex: "#800517",	name: "Deep Red"},
{ hex: "#660000",	name: "Red Blood"},
{ hex: "#551606",	name: "Blood Night"},
{ hex: "#560319",	name: "Dark Scarlet"},
{ hex: "#3D0C02",	name: "Black Bean"},
{ hex: "#3F000F",	name: "Chocolate Brown"},
{ hex: "#2B1B17",	name: "Midnight"},
{ hex: "#550A35",	name: "Purple Lily"},
{ hex: "#810541",	name: "Purple Maroon"},
{ hex: "#7D0541",	name: "Plum Pie"},
{ hex: "#7D0552",	name: "Plum Velvet"},
{ hex: "#872657",	name: "Dark Raspberry"},
{ hex: "#7E354D",	name: "Velvet Maroon"},
{ hex: "#7F4E52",	name: "Rosy-Finch"},
{ hex: "#7F525D",	name: "Dull Purple"},
{ hex: "#7F5A58",	name: "Puce"},
{ hex: "#997070",	name: "Rose Dust"},
{ hex: "#B1907F",	name: "Pastel Brown"},
{ hex: "#B38481",	name: "Rosy Pink"},
{ hex: "#BC8F8F",	name: "RosyBrown (W3C)"},
{ hex: "#C5908E",	name: "Khaki Rose"},
{ hex: "#C48793",	name: "Lipstick Pink"},
{ hex: "#C48189",	name: "Pink Brown"},
{ hex: "#C08081",	name: "Old Rose"},
{ hex: "#D58A94",	name: "Dusty Pink"},
{ hex: "#E799A3",	name: "Pink Daisy"},
{ hex: "#E8ADAA",	name: "Rose"},
{ hex: "#C9A9A6",	name: "Dusty Rose"},
{ hex: "#C4AEAD",	name: "Silver Pink"},
{ hex: "#E6C7C2",	name: "Gold Pink"},
{ hex: "#ECC5C0",	name: "Rose Gold"},
{ hex: "#FFCBA4",	name: "Deep Peach"},
{ hex: "#F8B88B",	name: "Pastel Orange"},
{ hex: "#EDC9AF",	name: "Desert Sand"},
{ hex: "#FFDDCA",	name: "Unbleached Silk"},
{ hex: "#FDD7E4",	name: "Pig Pink"},
{ hex: "#F2D4D7",	name: "Pale Pink"},
{ hex: "#FFE6E8",	name: "Blush"},
{ hex: "#FFE4E1",	name: "MistyRose (W3C)"},
{ hex: "#FFDFDD",	name: "Pink Bubble Gum"},
{ hex: "#FBCFCD",	name: "Light Rose"},
{ hex: "#FFCCCB",	name: "Light Red"},
{ hex: "#F6C6BD",	name: "Warm Pink"},
{ hex: "#FBBBB9",	name: "Deep Rose"},
{ hex: "#FFC0CB",	name: "Pink (W3C)"},
{ hex: "#FFB6C1",	name: "LightPink (W3C)"},
{ hex: "#FFB8BF",	name: "Soft Pink"},
{ hex: "#FAAFBE",	name: "Donut Pink"},
{ hex: "#FAAFBA",	name: "Baby Pink"},
{ hex: "#F9A7B0",	name: "Flamingo Pink"},
{ hex: "#FEA3AA",	name: "Pastel Pink"},
{ hex: "#E7A1B0",	name: "Rose Pink or Pink Rose"},
{ hex: "#E38AAE",	name: "Cadillac Pink"},
{ hex: "#F778A1",	name: "Carnation Pink"},
{ hex: "#E5788F",	name: "Pastel Rose"},
{ hex: "#E56E94",	name: "Blush Red"},
{ hex: "#DB7093",	name: "PaleVioletRed (W3C)"},
{ hex: "#D16587",	name: "Purple Pink"},
{ hex: "#C25A7C",	name: "Tulip Pink"},
{ hex: "#C25283",	name: "Bashful Pink"},
{ hex: "#E75480",	name: "Dark Pink"},
{ hex: "#F660AB",	name: "Dark Hot Pink"},
{ hex: "#FF69B4",	name: "HotPink (W3C)"},
{ hex: "#FC6C85",	name: "Watermelon Pink"},
{ hex: "#F6358A",	name: "Violet Red"},
{ hex: "#F52887",	name: "Hot Deep Pink"},
{ hex: "#FF007F",	name: "Bright Pink"},
{ hex: "#FF1493",	name: "DeepPink (W3C)"},
{ hex: "#F535AA",	name: "Neon Pink"},
{ hex: "#FF33AA",	name: "Chrome Pink"},
{ hex: "#FD349C",	name: "Neon Hot Pink"},
{ hex: "#E45E9D",	name: "Pink Cupcake"},
{ hex: "#E759AC",	name: "Royal Pink"},
{ hex: "#E3319D",	name: "Dimorphotheca Magenta"},
{ hex: "#E4287C",	name: "Pink Lemonade"},
{ hex: "#FA2A55",	name: "Red Pink"},
{ hex: "#E30B5D",	name: "Raspberry"},
{ hex: "#DC143C",	name: "Crimson (W3C)"},
{ hex: "#C32148",	name: "Bright Maroon"},
{ hex: "#C21E56",	name: "Rose Red"},
{ hex: "#C12869",	name: "Rogue Pink"},
{ hex: "#C12267",	name: "Burnt Pink"},
{ hex: "#CA226B",	name: "Pink Violet"},
{ hex: "#CC338B",	name: "Magenta Pink"},
{ hex: "#C71585",	name: "MediumVioletRed (W3C)"},
{ hex: "#C12283",	name: "Dark Carnation Pink"},
{ hex: "#B3446C",	name: "Raspberry Purple"},
{ hex: "#B93B8F",	name: "Pink Plum"},
{ hex: "#DA70D6",	name: "Orchid (W3C)"},
{ hex: "#DF73D4",	name: "Deep Mauve"},
{ hex: "#EE82EE",	name: "Violet (W3C)"},
{ hex: "#FF77FF",	name: "Fuchsia Pink"},
{ hex: "#F433FF",	name: "Bright Neon Pink"},
{ hex: "#FF00FF",	name: "Fuchsia or Magenta (W3C)"},
{ hex: "#E238EC",	name: "Crimson Purple"},
{ hex: "#D462FF",	name: "Heliotrope Purple"},
{ hex: "#C45AEC",	name: "Tyrian Purple"},
{ hex: "#BA55D3",	name: "MediumOrchid (W3C)"},
{ hex: "#A74AC7",	name: "Purple Flower"},
{ hex: "#B048B5",	name: "Orchid Purple"},
{ hex: "#B666D2",	name: "Rich Lilac"},
{ hex: "#D291BC",	name: "Pastel Violet"},
{ hex: "#915F6D",	name: "Mauve Taupe"},
{ hex: "#7E587E",	name: "Viola Purple"},
{ hex: "#614051",	name: "Eggplant"},
{ hex: "#583759",	name: "Plum Purple"},
{ hex: "#5E5A80",	name: "Grape"},
{ hex: "#4E5180",	name: "Purple Navy"},
{ hex: "#6A5ACD",	name: "SlateBlue (W3C)"},
{ hex: "#6960EC",	name: "Blue Lotus"},
{ hex: "#5865F2",	name: "Blurple"},
{ hex: "#736AFF",	name: "Light Slate Blue"},
{ hex: "#7B68EE",	name: "MediumSlateBlue (W3C)"},
{ hex: "#7575CF",	name: "Periwinkle Purple"},
{ hex: "#6667AB",	name: "Very Peri"},
{ hex: "#6F2DA8",	name: "Bright Grape"},
{ hex: "#6C2DC7",	name: "Purple Amethyst"},
{ hex: "#6A0DAD",	name: "Bright Purple"},
{ hex: "#5453A6",	name: "Deep Periwinkle"},
{ hex: "#483D8B",	name: "DarkSlateBlue (W3C)"},
{ hex: "#4E387E",	name: "Purple Haze"},
{ hex: "#571B7E",	name: "Purple Iris"},
{ hex: "#4B0150",	name: "Dark Purple"},
{ hex: "#36013F",	name: "Deep Purple"},
{ hex: "#2E1A47",	name: "Midnight Purple"},
{ hex: "#461B7E",	name: "Purple Monster"},
{ hex: "#4B0082",	name: "Indigo (W3C)"},
{ hex: "#342D7E",	name: "Blue Whale"},
{ hex: "#663399",	name: "RebeccaPurple (W3C)"},
{ hex: "#6A287E",	name: "Purple Jam"},
{ hex: "#8B008B",	name: "DarkMagenta (W3C)"},
{ hex: "#800080",	name: "Purple (W3C)"},
{ hex: "#86608E",	name: "French Lilac"},
{ hex: "#9932CC",	name: "DarkOrchid (W3C)"},
{ hex: "#9400D3",	name: "DarkViolet (W3C)"},
{ hex: "#8D38C9",	name: "Purple Violet"},
{ hex: "#A23BEC",	name: "Jasmine Purple"},
{ hex: "#B041FF",	name: "Purple Daffodil"},
{ hex: "#842DCE",	name: "Clematis Violet"},
{ hex: "#8A2BE2",	name: "BlueViolet (W3C)"},
{ hex: "#7A5DC7",	name: "Purple Sage Bush"},
{ hex: "#7F38EC",	name: "Lovely Purple"},
{ hex: "#9D00FF",	name: "Neon Purple"},
{ hex: "#8E35EF",	name: "Purple Plum"},
{ hex: "#893BFF",	name: "Aztech Purple"},
{ hex: "#9370DB",	name: "MediumPurple (W3C)"},
{ hex: "#8467D7",	name: "Light Purple"},
{ hex: "#9172EC",	name: "Crocus Purple"},
{ hex: "#9E7BFF",	name: "Purple Mimosa"},
{ hex: "#CCCCFF",	name: "Periwinkle"},
{ hex: "#DCD0FF",	name: "Pale Lilac"},
{ hex: "#967BB6",	name: "Lavender Purple"},
{ hex: "#B09FCA",	name: "Rose Purple"},
{ hex: "#C8A2C8",	name: "Lilac"},
{ hex: "#E0B0FF",	name: "Mauve"},
{ hex: "#D891EF",	name: "Bright Lilac"},
{ hex: "#C38EC7",	name: "Purple Dragon"},
{ hex: "#DDA0DD",	name: "Plum (W3C)"},
{ hex: "#E6A9EC",	name: "Blush Pink"},
{ hex: "#F2A2E8",	name: "Pastel Purple"},
{ hex: "#F9B7FF",	name: "Blossom Pink"},
{ hex: "#C6AEC7",	name: "Wisteria Purple"},
{ hex: "#D2B9D3",	name: "Purple Thistle"},
{ hex: "#D8BFD8",	name: "Thistle (W3C)"},
{ hex: "#DFD3E3",	name: "Purple White"},
{ hex: "#E9CFEC",	name: "Periwinkle Pink"},
{ hex: "#FCDFFF",	name: "Cotton Candy"},
{ hex: "#EBDDE2",	name: "Lavender Pinocchio"},
{ hex: "#E1D9D1",	name: "Dark White"},
{ hex: "#E9E4D4",	name: "Ash White"},
{ hex: "#EDE6D6",	name: "White Chocolate"},
{ hex: "#FAF0DD",	name: "Soft Ivory"},
{ hex: "#F8F0E3",	name: "Off White"},
{ hex: "#F8F6F0",	name: "Pearl White"},
{ hex: "#F3E8EA",	name: "Red White"},
{ hex: "#FFF0F5",	name: "LavenderBlush (W3C)"},
{ hex: "#FDEEF4",	name: "Pearl"},
{ hex: "#FFF9E3",	name: "Egg Shell"},
{ hex: "#FEF0E3",	name: "OldLace (W3C)"},
{ hex: "#FAF0E6",	name: "Linen (W3C)"},
{ hex: "#FFF5EE",	name: "SeaShell (W3C)"},
{ hex: "#F9F6EE",	name: "Bone White"},
{ hex: "#FAF5EF",	name: "Rice"},
{ hex: "#FFFAF0",	name: "FloralWhite (W3C)"},
{ hex: "#FFFFF0",	name: "Ivory (W3C)"},
{ hex: "#FFFFF4",	name: "White Gold"},
{ hex: "#FFFFF7",	name: "Light White"},
{ hex: "#F5F5F5",	name: "WhiteSmoke (W3C)"},
{ hex: "#FBFBF9",	name: "Cotton"},
{ hex: "#FFFAFA",	name: "Snow (W3C)"},
{ hex: "#FEFCFF",	name: "Milk White"},
{ hex: "#FFFEFA",	name: "Half White"},
{ hex: "#FFFFFF",	name: "White (W3C)"},
]